# .bandit.yaml: configuration for Bandit security linter (https://github.com/PyCQA/bandit)
# https://bandit.readthedocs.io/en/latest/config.html
# Run Bandit from project root like so: bandit -r -c .bandit.yaml .

# Note that any inline exceptions to the linter (signified with a trailing "# nosec" comment)
# must contain a nearby comment explaining why the exception is considered safe or necessary.

# See <URL: https://bandit.readthedocs.io/en/latest/blacklists/index.html > for more details.
exclude_dirs: [venv, tests, utils]
